const fs = require('node:fs');
const path = require('node:path');
const root = path.resolve(__dirname, '..');
const read = name => fs.readFileSync(path.join(root, 'src', name), 'utf8');
fs.mkdirSync(path.join(root, 'dist'), {recursive:true});
const bundle = '// Generated by npm run build. Edit src/, not this file.\n' +
  'var JEV_SETTINGS_HTML = ' + JSON.stringify(read('settings.html')) + ';\n' +
  ['core.js', 'addon.js', 'samples.js'].map(read).join('\n');
fs.writeFileSync(path.join(root, 'dist/Code.gs'), bundle);
fs.copyFileSync(path.join(root, 'src/appsscript.json'), path.join(root, 'dist/appsscript.json'));
console.log('Built dist/Code.gs and dist/appsscript.json');
